Build and publish Linux tar.gz and AppImage

diff --git a/.github/workflows/linux.yml b/.github/workflows/linux.yml
--- a/.github/workflows/linux.yml
+++ b/.github/workflows/linux.yml
@@ -10,7 +10,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
-      - run: sudo apt-get install qt5-qmake qtdeclarative5-dev
+      - run: sudo apt-get install qt5-default qt5-qmake qtdeclarative5-dev
 
       # For 'Verify all' tests
       - run: sudo apt-get install lz4 python3 xvfb
@@ -46,10 +46,13 @@ jobs:
           sed -i "s,^gameboy_rgbasm_dir =.*,gameboy_rgbasm_dir=${PWD}/tools/rgbds/build/src," Publish/publish_linux/trse.ini
           sed -i "s,^pasmo =.*,pasmo=${PWD}/tools/pasmo/pasmo," Publish/publish_linux/trse.ini
 
-      - run: qmake TRSE.pro
-      - run: make
+      - name: Build TRSE
+        run: |
+          # PREFIX is here for the AppImage build
+          qmake PREFIX=/usr TRSE.pro
+          make -j 2
 
-      - name: Verify all
+      - name: Verify tutorials
         run: |
           mkdir bin
           cp trse bin/
@@ -59,3 +62,47 @@ jobs:
           cp Publish/publish_linux/trse.ini ~/.local/share/TRSE/
           cd bin
           xvfb-run --auto-servernum python3 ../Publish/verify_all/verify_all.py `pwd`/trse
+
+      # Construct and publish the linux binary package
+      - name: Build tar.gz
+        run: cd Publish/publish_linux && ./publish nightly
+      - name: Publish tar.gz
+        uses: ColinPitrat/update-release@master
+        with:
+          release: nightly
+          message: Nightly build
+          body: The latest automated nightly build of TRSE which succeeded. This is the recommended version to use.
+          files: Publish/publish_linux/trse_linux64.tar.gz
+          prerelease: false
+          token: ${{ secrets.GITHUB_TOKEN }}
+
+      # Construct and publish the AppImage
+      # Note: we're relying on the previous call to publish_linux to have copied everything that is needed under Publish/publish_linux/trse
+      # TODO(ColinPitrat): Migrate the whole of publish_linux to the `make install` generated by qmake
+      - name: Build AppImage
+        run: |
+          make INSTALL_ROOT=Publish/publish_linux/trse install; find Publish/publish_linux/trse
+          cd Publish/publish_linux/
+          # TODO(ColinPitrat): This cleanup wouldn't be necessary if we were using `make install` to do the full publish part (we would need 2 make install calls though: one for tar.gz and one for AppImage)
+          rm -rf trse/{bin,lib}
+          # We need (at least some of) those dirs in both places, which is a bit weird.
+          # TODO(ColinPitrat): Understand why and try to have them in only one place.
+          cp -r trse/{project_templates,themes,tutorials,units} trse/usr/
+
+          wget -c https://github.com/$(wget -q https://github.com/probonopd/go-appimage/releases -O - | grep "appimagetool-.*-x86_64.AppImage" | head -n 1 | cut -d '"' -f 2) -O appimagetool
+          chmod +x appimagetool
+          ./appimagetool -s deploy trse/usr/share/applications/trse.desktop
+
+          find trse | grep ld-linux
+          chmod a+x trse/lib*/ld-linux-* trse/usr/lib*/ld-linux-* || echo "chmod failed"
+          chmod 755 trse
+          VERSION=nightly ARCH=x86_64 ./appimagetool ./trse
+      - name: Publish AppImage
+        uses: ColinPitrat/update-release@master
+        with:
+          release: nightly
+          message: Nightly build
+          body: The latest automated nightly build of TRSE which succeeded. This is the recommended version to use.
+          files: Publish/publish_linux/TRSE-nightly-x86_64.AppImage
+          prerelease: false
+          token: ${{ secrets.GITHUB_TOKEN }}
