Separate the linux build and appimage build. Apply advices from https://github.com/actions/virtual-environments/issues/3804

diff --git a/.github/workflows/linux-appimage.yml b/.github/workflows/linux-appimage.yml
--- a/.github/workflows/linux-appimage.yml
+++ b/.github/workflows/linux-appimage.yml
@@ -1,4 +1,6 @@
-name: linux
+# Separate build for the AppImage as it's been failing lately so we want a distinct notification for it.
+# This also allows to experiment without affecting the regular linux build.
+name: linux-appimage
 
 on:
   push:
@@ -143,6 +145,39 @@ jobs:
           prerelease: false
           token: ${{ secrets.GITHUB_TOKEN }}
 
+      # Construct and publish the AppImage
+      # Note: we're relying on the previous call to publish_linux to have copied everything that is needed under Publish/publish_linux/trse
+      # TODO(ColinPitrat): Migrate the whole of publish_linux to the `make install` generated by qmake
+      - name: Build AppImage
+        run: |
+          export ANDROID_HOME=/usr/local/lib/android/sdk
+          export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64/qt/lib:${LD_LIBRARY_PATH}
+          make INSTALL_ROOT=Publish/publish_linux/trse install; find Publish/publish_linux/trse
+          cd Publish/publish_linux/
+          # TODO(ColinPitrat): This cleanup wouldn't be necessary if we were using `make install` to do the full publish part (we would need 2 make install calls though: one for tar.gz and one for AppImage)
+          rm -rf trse/{bin,lib}
+          # We need (at least some of) those dirs in both places, which is a bit weird.
+          # TODO(ColinPitrat): Understand why and try to have them in only one place.
+          cp -r trse/{project_templates,themes,tutorials,units} trse/usr/
+
+          wget --tries=3 -c https://github.com/$(wget -q https://github.com/probonopd/go-appimage/releases -O - | grep "appimagetool-.*-x86_64.AppImage" | head -n 1 | cut -d '"' -f 2) -O appimagetool
+          chmod +x appimagetool
+          ./appimagetool -s deploy trse/usr/share/applications/trse.desktop
+
+          find trse | grep ld-linux
+          chmod a+x trse/lib*/ld-linux-* trse/usr/lib*/ld-linux-* || echo "chmod failed"
+          chmod 755 trse
+          VERSION=nightly ARCH=x86_64 ./appimagetool ./trse
+      - name: Publish AppImage
+        uses: ColinPitrat/update-release@master
+        with:
+          release: nightly
+          message: Nightly build
+          body: TRSE ${{ steps.version.outputs.TRSE_VERSION }} <br/> The latest automated nightly build of TRSE which succeeded. This is the recommended version to use.
+          files: Publish/publish_linux/TRSE-nightly-x86_64.AppImage
+          prerelease: false
+          token: ${{ secrets.GITHUB_TOKEN }}
+
       - name: Verify tutorials
         run: |
           mkdir bin
@@ -163,4 +198,4 @@ jobs:
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
         with:
           channel: #bugs
-          text: "[GitHub Actions Notification] Linux build failed: ${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}"
+          text: "[GitHub Actions Notification] Linux AppImage build failed: ${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}"
