Attempt to build and release OK64 as part of TRSE for windows.

diff --git a/.github/workflows/win32-msvc.yml b/.github/workflows/win32-msvc.yml
--- a/.github/workflows/win32-msvc.yml
+++ b/.github/workflows/win32-msvc.yml
@@ -26,9 +26,18 @@ jobs:
           version=$(grep "define \(MAJOR\|FEATURE\|NIGHTLY\)" source/LeLib/data.cpp | awk '{ print $3 }' | xargs | sed 's/ /\./g')
           echo "::set-output name=TRSE_VERSION::${version}"
       - uses: microsoft/setup-msbuild@v1
+
+      # For QT6 build. Commented out because QtMultimedia, which is needed to build OK64, is not available in Qt 6.0 and 6.1.
+      # Hopefully should be reintroduced in Qt 6.2.
+      #- uses: jurplel/install-qt-action@v2
+      #  with:
+      #    version: '6.0.1'
+      #    tools: 'tools_ifw,4,qt.tools.ifw.40 tools_qtcreator,4,qt.tools.qtcreator'
+
+      # For QT5 build.
       - uses: jurplel/install-qt-action@v2
         with:
-          version: '6.0.1'
+          version: '5.15.2'
           tools: 'tools_ifw,4,qt.tools.ifw.40 tools_qtcreator,4,qt.tools.qtcreator'
 
       - name: Build TRSE
@@ -38,6 +47,15 @@ jobs:
           qmake TRSE.pro
           D:\a\TRSE\Qt\Tools\QtCreator\bin\jom.exe -j 2 -f Makefile.Release
 
+      - name: Build OK64
+        shell: cmd
+        run: |
+          git clone https://github.com/leuat/OK64.git
+          cd OK64/OK64
+          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
+          qmake INCLUDEPATH=$OK64dir/resid/include QMAKE_LFLAGS=-Wl,-L$OK64dir/resid/lib/ OK64.pro
+          D:\a\TRSE\Qt\Tools\QtCreator\bin\jom.exe -j 2 -f Makefile.Release
+
       # We do not reuse Publish/publish_win/PublishWindows.cmd because copying the libs & plugins is easier with bash
       - name: Build zip
         shell: bash
@@ -45,6 +63,7 @@ jobs:
           mkdir Publish/publish_win/trse
           cd Publish/publish_win/trse
           cp ../../../release/trse.exe .
+          cp ../../../OK64/OK64/OK64.exe .
           # Copy themes, tutorials, project_templates and units
           cp -r ../../source/* .
           cp -r ../../tutorials .
@@ -80,6 +99,9 @@ jobs:
           echo "Copy trse.exe dependencies"
           ldd trse.exe | grep -v -i -f ../ignore_dlls.txt | awk '{ print $3 }' | sort -u
           ldd trse.exe | grep -v -i -f ../ignore_dlls.txt | awk '{ print $3 }' | sort -u | xargs -I _ bash -c 'cp _ ./ || echo "failed to copy _"'
+          echo "Copy OK64.exe dependencies"
+          ldd OK64.exe | grep -v -i -f ../ignore_dlls.txt | awk '{ print $3 }' | sort -u
+          ldd OK64.exe | grep -v -i -f ../ignore_dlls.txt | awk '{ print $3 }' | sort -u | xargs -I _ bash -c 'cp _ ./ || echo "failed to copy _"'
           cd ..
           7z a trse_win.zip trse
 
