Publish archive for windows during nightly build.

diff --git a/.github/workflows/win32-msvc.yml b/.github/workflows/win32-msvc.yml
--- a/.github/workflows/win32-msvc.yml
+++ b/.github/workflows/win32-msvc.yml
@@ -16,20 +16,52 @@ jobs:
           version: '6.0.1'
           tools: 'tools_ifw,4,qt.tools.ifw.40 tools_qtcreator,4,qt.tools.qtcreator'
 
-      # Build TRSE
-      - shell: cmd
+      - name: Build TRSE
+        shell: cmd
         run: |
           call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
           qmake TRSE.pro
-          D:\a\TRSE\Qt\Tools\QtCreator\bin\jom.exe -f Makefile.Release
+          D:\a\TRSE\Qt\Tools\QtCreator\bin\jom.exe -j 2 -f Makefile.Release
 
-      # TODO(ColinPitrat): Review all this
-      # All the steps below are not necessary (for now) but document what needs
-      # to be done for TRSE to work under linux.
-      # cf. README.md
-      - run: copy Publish/source/themes release/
-      # This should be a symbolic link
-      - run: copy Publish/tutorials release/
-      # Not clear what should be done about units
-      # Now you're ready to run:
-      # ./release/trse.exe
+      # We do not reuse Publish/publish_win/PublishWindows.cmd because copying the libs & plugins is easier with bash
+      - name: Build zip
+        shell: bash
+        run: |
+          mkdir Publish/publish_win/trse
+          cd Publish/publish_win/trse
+          cp ../../../release/trse.exe .
+          cp -r ../../tutorials .
+          cp -r ../../project_templates .
+          cp -r ../../../units .
+          echo "Copy all required plugins"
+          # qt_lib_dir must be retrieved before copying the DLLs as after that, all the DLLs are resolved locally
+          qt_lib_dir=$(ldd trse.exe | awk '{ print $3 }' | grep "/Qt/" | sed 's,/Qt/.*,/Qt/,' | head -n 1)
+          echo "qt_lib_dir: '${qt_lib_dir}'"
+          # The file is converted to dos format at checkout, we don't want the carriage returns.
+          dos2unix ../plugins.txt
+          while read plugin
+          do
+            echo "  Looking for '${plugin}'"
+            lib=$(find "${qt_lib_dir}" | grep "${plugin}" | head -n 1 || echo "")
+            if [ -z "${lib}" ]
+            then
+              echo "  - ${lib} NOT FOUND"
+            else
+              echo "  - ${lib} (${plugin})"
+              mkdir -p $(dirname "plugins/${plugin}")
+              cp "${lib}" "plugins/${plugin}"
+            fi
+          done < ../plugins.txt
+          echo "Copy all required libs"
+          ldd trse.exe | awk '{ print $3 }' | sort -u | xargs -I _ cp _ ./
+          zip trse_win.zip trse
+
+      - name: Publish zip
+        uses: ColinPitrat/update-release@master
+        with:
+          release: nightly
+          message: Nightly build
+          body: The latest automated nightly build of TRSE which succeeded. This is the recommended version to use.
+          files: Publish/publish_win/trse_win.zip
+          prerelease: false
+          token: ${{ secrets.GITHUB_TOKEN }}
