Is this dos2unix again?

diff --git a/.github/workflows/win32-msvc.yml b/.github/workflows/win32-msvc.yml
--- a/.github/workflows/win32-msvc.yml
+++ b/.github/workflows/win32-msvc.yml
@@ -41,6 +41,7 @@ jobs:
           echo "qt_lib_dir: '${qt_lib_dir}'"
           # The file is converted to dos format at checkout, we don't want the carriage returns.
           dos2unix ../plugins.txt
+          dos2unix ../ignore_dlls.txt
           while read plugin
           do
             echo "  Looking for '${plugin}'"
@@ -58,15 +59,15 @@ jobs:
               grep --help
               ldd "${lib}" | grep -v -i -F -f ../ignore_dlls.txt || echo "ldd | grep failed"
               echo "    Cleaned list:"
-              ldd "${lib}" | grep -v -i -F -f ../ignore_dlls.txt | awk '{ print $3 }' || echo "ldd | grep | awk failed"
+              ldd "${lib}" | grep -v -i -f ../ignore_dlls.txt | awk '{ print $3 }' || echo "ldd | grep | awk failed"
               echo "    Copying its dependencies:"
-              ldd "${lib}" | grep -v -i -F -f ../ignore_dlls.txt | awk '{ print $3 }' | sort -u || echo "ldd | grep | awk | sort failed"
-              ldd "${lib}" | grep -v -i -F -f ../ignore_dlls.txt | awk '{ print $3 }' | sort -u | xargs -I _ bash -c 'cp _ ./ || echo "failed to copy _"' || echo "ldd | grep | awk | sort | xargs bash failed"
+              ldd "${lib}" | grep -v -i -f ../ignore_dlls.txt | awk '{ print $3 }' | sort -u || echo "ldd | grep | awk | sort failed"
+              ldd "${lib}" | grep -v -i -f ../ignore_dlls.txt | awk '{ print $3 }' | sort -u | xargs -I _ bash -c 'cp _ ./ || echo "failed to copy _"' || echo "ldd | grep | awk | sort | xargs bash failed"
             fi
           done < ../plugins.txt
           echo "Copy all required libs"
-          ldd trse.exe | grep -v -i -F -f ../ignore_dlls.txt | awk '{ print $3 }' | sort -u || echo "ldd | grep | awk | sort failed"
-          ldd trse.exe | grep -v -i -F -f ../ignore_dlls.txt | awk '{ print $3 }' | sort -u | xargs -I _ bash -c 'cp _ ./ || echo "failed to copy _"' || echo "ldd | grep | awk | sort | xargs bashfailed"
+          ldd trse.exe | grep -v -i -f ../ignore_dlls.txt | awk '{ print $3 }' | sort -u || echo "ldd | grep | awk | sort failed"
+          ldd trse.exe | grep -v -i -f ../ignore_dlls.txt | awk '{ print $3 }' | sort -u | xargs -I _ bash -c 'cp _ ./ || echo "failed to copy _"' || echo "ldd | grep | awk | sort | xargs bashfailed"
           # This find | rm shouldn't be needed once the mechanism to ignore undesired DLLs works
           echo "Remove DLLs that shouldn't be included: "
           cat ../ignore_dlls.txt
